# Generated by Django 4.2.7 on 2023-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dengue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
                ('Cases', models.PositiveIntegerField()),
                ('Deaths', models.PositiveIntegerField()),
                ('Date', models.DateField()),
                ('Region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dengue_dataset',
            },
        ),
    ]
